- src: https://unpkg.com/@webcomponents/custom-elements@1.4.2/custom-elements.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  noModule: true
  defer: true
  integrity: sha384-xyhN4T4+9VPh8uXl6uWjGzsqwNXN9C2tla8b6zSrSqYlMFUoeCdoxiEJU0js+GNE
- src: https://unpkg.com/@shgysk8zer0/polyfills@0.5.3/browser.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-OLBgp1GsljhM2TJ+sbHjaiH9txEUvgdDTAzHv2P24donTt6/529l+9Ua0vFImLlb
  defer: true
- src: /js/index.min.js
  referrerPolicy: no-referrer
  defer: true
