---
author: Chris Zuber
title: Kern Valley Guide
name: Kern Valley Guide
url: https://guide.kernvalley.us
markdown: kramdown
version: 1.0.0
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
viewport: "width=device-width, viewport-fit=cover"
robots: 'follow, index'
referrer: no-referrer
manifest: /webapp.webmanifest
tiles-config: /browserconfig.xml
service_worker: /service-worker.js
og-type: website
keep-kern-clean: true
description: Your virtual guide to exploring the Kern River Valley. Get the knowledge of locals at your fingertips!
mobile-web-app-capable: true
canonical: https://guide.kernvalley.us
thumbnail:
  url: https://cdn.kernvalley.us/img/thumbnail/krv-guide.png
  width: 1280
  height: 720
keywords:
  - directory
  - guide
  - businesses
  - kern valley
  - kern river valley
repository:
  username: kernvalley
  project: guide.kernvalley.us
  title: Kern Valley Guide
twitter: kern_valley
# feed:
#   url: /feed.rss
#   type: application/rss+xml
icons: /img/icons.svg
# discus-identifier:
# google-analytics:
# ad-sense:
webmaster-verifications:
#   google:
  bing: 14343D3F998AB3FEE56B299A7F3E5CDB
defaults: []
plugins:
  - jekyll-gist
  - jekyll-youtube
  - jekyll-admin
  - jekyll-watch
  - jekyll-paginate
include:
# Folders with dotfiles are ignored by default.
  - .well-known
  - _headers
  - _redirects
exclude:
  - ".gitkeep"
  - "*.rb"
  - "*.gemspec"
  - "*.php"
  - "*.sh"
  - "*.csv"
  - "*.sfd"
  - "*.ai"
  - "*.psd"
  - "*.sketch"
  - "*.yml"
  - "*.lock"
  - "*.log"
  - "*.config.js"
  - ".gitkeep"
  - docs/
  - "/.github/"
  - Gemfile
  - node_modules/
  - palette.xml
  - README.md
  - LICENSE
  - "/img/octicons/*.md"
  - "/img/octicons/LICENSE"
  - "/img/octicons/script"
  - "/img/adwaita-icons/docs"
  - "/img/adwaita-icons/LICENSE"
