---
author: Chris Zuber
title: Kern Valley Business Guide
url: https://guide.kernvalley.us
markdown: kramdown
version: 1.0.0
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
viewport: "width=device-width, viewport-fit=cover"
robots: 'follow, index'
referrer: no-referrer
manifest: /webapp.webmanifest
tiles-config: /browserconfig.xml
service_worker: /service-worker.js
og-type: website
keep-kern-clean: true
description: A directory of local businesses in the Kern River Valley
mobile-web-app-capable: true
canonical: https://guide.kernvalley.us
keywords:
  - directory
  - guide
  - businesses
  - kern valley
  - kern river valley
thumbnail:
  url: https://i.imgur.com/bWudF1el.jpg
  width: 640
  height: 315
repository:
  username: kernvalley
  project: guide.kernvalley.us
  title: Kern Valley Guide
twitter: kern_valley
# feed:
#   url: /feed.rss
#   type: application/rss+xml
icons: /img/icons.svg
# discus-identifier:
# google-analytics:
# ad-sense:
# webmaster-verifications:
#   google:
#   bing:
defaults: []
plugins:
  - jekyll-gist
  - jekyll-youtube
  - jekyll-admin
  - jekyll-watch
  - jekyll-paginate
include:
# Folders with dotfiles are ignored by default.
  - .well-known
  - _headers
  - _redirects
exclude:
  - ".gitkeep"
  - "*.rb"
  - "*.gemspec"
  - "*.php"
  - "*.sh"
  - "*.csv"
  - "*.sfd"
  - "*.ai"
  - "*.psd"
  - "*.sketch"
  - "*.yml"
  - "*.lock"
  - "*.log"
  - "*.config.js"
  - ".gitkeep"
  - docs/
  - "/.github/"
  - Gemfile
  - node_modules/
  - palette.xml
  - README.md
  - LICENSE
  - "/img/octicons/*.md"
  - "/img/octicons/LICENSE"
  - "/img/octicons/script"
  - "/img/adwaita-icons/docs"
  - "/img/adwaita-icons/LICENSE"
