name: Kern Valley Guide
shortName: KRV Guide
id: KRVGuide
startUrl: /?utm_source=pwa&utm_medium=pwa&utm_campaign=pwa
version: 1.0.2
lang: en
dir: ltr
display: standalone
orientation: any
description: Your virtual guide to exploring the Kern River Valley. Get the knowledge of locals at your fingertips!
icons-file: /img/icons.svg
theme:
  color: '#008000'
  background: '#242424'
icons:
  - src: /img/favicon.svg
    type: image/svg+xml
    sizes: 150x150
    purpose: maskable any
  - src: /img/apple-touch-icon.png
    rel: apple-touch-icon
    type: image/png
    sizes: 180x180
  - src: /img/icon-512.png
    type: image/png
    sizes: 512x512
    purpose: maskable any
  - src: /img/icon-192.png
    type: image/png
    sizes: 192x192
    purpose: maskable any
  - src: /img/icon-32.png
    type: image/png
    sizes: 32x32
  - src: /img/icon-16.png
    type: image/png
    sizes: 16x16
screenshots:
  - src: https://i.imgur.com/bWudF1eh.jpg
    sizes: 1024x504
    type: image/jpeg
  - src: https://i.imgur.com/bWudF1el.jpg
    sizes: 640x315
    type: image/jpeg
  - src: https://i.imgur.com/bWudF1em.jpg
    sizes: 320x158
    type: image/jpeg
  - src: https://i.imgur.com/bWudF1et.jpg
    sizes: 160x79
    type: image/jpeg
# https://web.dev/app-shortcuts/
shortcuts:
  - name: Dining
    url: /dining?utm_source=shortcut&utm_medium=pwa&utm_campaign=pwa&utm_content=dining
    description: Dining Page on KRV Guide
    icons:
      - src: /img/shortcuts/restaurant-192.png
        type: image/png
        sizes: 192x192
      - src: /img/shortcuts/restaurant-32.png
        type: image/png
        sizes: 32x32
  - name: Stores
    url: /stores?utm_source=shortcut&utm_medium=pwa&utm_campaign=pwa&utm_content=stores
    description: Grocery and other Stores Page on KRV Guide
    icons:
      - src: /img/shortcuts/shopping-192.png
        type: image/png
        sizes: 192x192
      - src: /img/shortcuts/shopping-32.png
        type: image/png
        sizes: 32x32
  - name: Activities
    url: /activities?utm_source=shortcut&utm_medium=pwa&utm_campaign=pwa&utm_content=activities
    description: List of recreational activities in the Kern River Valley with extended contact info
    icons:
      - src: /img/shortcuts/activities-192.png
        type: image/png
        sizes: 192x192
      - src: /img/shortcuts/activities-32.png
        type: image/png
        sizes: 32x32
  - name: Other
    url: /othe?utm_source=shortcut&utm_medium=pwa&utm_campaign=pwa&utm_content=other
    description: Misc. listings Page on KRV Guide
    icons:
      - src: /img/shortcuts/business-192.png
        type: image/png
        sizes: 192x192
      - src: /img/shortcuts/business-32.png
        type: image/png
        sizes: 32x32
iarc_rating_id: 6b80d8b3-64c2-42f8-8727-f66e3e1e3ce5
related_applications:
  - platform: webapp
    url: /webapp.webmanifest
  - platform: play
    id: "us.kernvalley.guide.twa"
    url: https://play.google.com/store/apps/details?id=us.kernvalley.guide.twa
  #   url: "#"
  # - platform: itunes
  #   url: "#"
  # - platform: windows
  #   url: "#"
features:
  - List businesses in the Kern River Valley by category
  - Search for business by name
  - Find phone numbers, addresses, websites, business hours, and more
  - Share contact info to other apps
  - Offline functionality
# https://github.com/w3c/manifest/wiki/Categories
categories:
  - travel
  - business
  - productivity
  - utilities
